language: c


env:
        global:
        - PDVERSION='0.47-1'
        - secure: "DA85V8jBW8C6n6z9qiGufU1BK1atVUsvnceHIuf0pG64faZBNLg93J3SfyV2/NN0C4AVAaVHSM+F8XR8Ba8GdxHbW8OGJR+vcgr6ZFg5Qai/xmMJm5MfcR/oPFj8nuMnT61rb6Jm5QpuURRwAjio+x7wCHQJkkpH1TiQF9mV2Tk="

matrix:
        include:
        - env: PLATFORM='linux64'
          os: linux
          dist: trusty
          sudo: required
          compiler: gcc

        - env: PLATFORM='linux32' CHROOTDIR='/opt/crosscompilation'
          os: linux
          dist: trusty
          sudo: required
          compiler: gcc

        - env: PLATFORM='osx'
          os: osx

        - env: PLATFORM='windows'
          os: linux
          dist: trusty
          sudo: required
          compiler: gcc

before_install: bash ./travis-build/${PLATFORM}_before_install.sh
script: bash ./travis-build/${PLATFORM}_script.sh
after_success: bash ./travis-build/${PLATFORM}_pack.sh
deploy:
    skip_cleanup: true
    provider: script
    script: bash ./travis-build/upload.sh
    on: 
        all_branches: true
